# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6147f33a2ae7bdc1046c9c6b3577fd05485bc6480aed0cd31c6bffe1be51c35daff62a437215ca11388378bde57aa67c1ffb9a087f0656ca9f21707d9f7a98af

test:
  secret_key_base: a8b0289afabd02ab600b401d44d8f87da4e56965ef7b82d0db640f50bed3d77338c78e4309c79469d4501394626ba02bb5cb67cb0fd4cc1dae2e908fde7322e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
